export const USER_CREATED = 'USER_CREATED';
export const INVENTORY_ADDED = 'INVENTORY_ADDED';
export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART';
export const USER_CONFIRMED = 'USER_CONFIRMED';
export const USER_ADDED = 'USER_ADDED';
export const USER_LOGGED = 'USER_LOGGED';
export const MANDADERO_SELECTED = 'MANDADERO_SELECTED';




